### ISSUE TITLE
Unauthorized access of users reports

### ISSUE THREAD

**Issue by xosteve26** [xosteve26/PULSTRAT#31]

**Comment by syed-saif** [comment]
Error fixed in commit fadf709bc3bd6dfc64254eb7b9c3c5897b303596 at [backend/xmed/views.py](https://github.com/xosteve26/PULSTRAT/blob/19ec132bec65262167b48868f8011c7e8e895a20/backend/xmed/views.py#L165-L167)  @ the lines 165-167
